server:
  port: 8082
  servlet:
    context-path: /

spring:
  profiles:
    active: local
  application:
    name: demo-api
  datasource-mysql:
    jdbc-url: jdbc:mysql://127.0.0.1:3306/web?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver